// <auto-generated />
using System;
using Flush_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flush_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230912204238_CreateMealAndRelations")]
    partial class CreateMealAndRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flush_API.Models.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Alcohol")
                        .HasColumnType("boolean");

                    b.Property<bool>("ArtificialAdditive")
                        .HasColumnType("boolean");

                    b.Property<bool>("ArtificialSweetener")
                        .HasColumnType("boolean");

                    b.Property<bool>("CarbonatedBeverage")
                        .HasColumnType("boolean");

                    b.Property<double>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<bool>("CoffeeTea")
                        .HasColumnType("boolean");

                    b.Property<bool>("DairyProduct")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("FODMAP")
                        .HasColumnType("boolean");

                    b.Property<double>("Fats")
                        .HasColumnType("double precision");

                    b.Property<bool>("FattyOrGreasyFood")
                        .HasColumnType("boolean");

                    b.Property<bool>("Gluten")
                        .HasColumnType("boolean");

                    b.Property<bool>("HighFiberFood")
                        .HasColumnType("boolean");

                    b.Property<bool>("HighSugarFood")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ProcessedFriedFood")
                        .HasColumnType("boolean");

                    b.Property<double>("Proteins")
                        .HasColumnType("double precision");

                    b.Property<bool>("Spicy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("FoodItem");
                });

            modelBuilder.Entity("Flush_API.Models.IbsCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Count")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("IbsCount");
                });

            modelBuilder.Entity("Flush_API.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Alcohol")
                        .HasColumnType("boolean");

                    b.Property<bool>("ArtificialAdditive")
                        .HasColumnType("boolean");

                    b.Property<bool>("ArtificialSweetener")
                        .HasColumnType("boolean");

                    b.Property<bool>("CarbonatedBeverage")
                        .HasColumnType("boolean");

                    b.Property<double>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<bool>("CoffeeTea")
                        .HasColumnType("boolean");

                    b.Property<bool>("DairyProduct")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FODMAP")
                        .HasColumnType("boolean");

                    b.Property<double>("Fats")
                        .HasColumnType("double precision");

                    b.Property<bool>("FattyOrGreasyFood")
                        .HasColumnType("boolean");

                    b.Property<bool>("Gluten")
                        .HasColumnType("boolean");

                    b.Property<bool>("HighFiberFood")
                        .HasColumnType("boolean");

                    b.Property<bool>("HighSugarFood")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ProcessedFriedFood")
                        .HasColumnType("boolean");

                    b.Property<double>("Proteins")
                        .HasColumnType("double precision");

                    b.Property<bool>("Spicy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("Flush_API.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("Flush_API.Models.MealFoodItem", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("integer");

                    b.HasKey("MealId", "FoodItemId");

                    b.HasIndex("FoodItemId");

                    b.ToTable("MealFoodItems");
                });

            modelBuilder.Entity("Flush_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Flush_API.Models.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("Flush_API.Models.MealFoodItem", b =>
                {
                    b.HasOne("Flush_API.Models.FoodItem", "FoodItem")
                        .WithMany("MealFoodItems")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flush_API.Models.Meal", "Meal")
                        .WithMany("MealFoodItems")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Flush_API.Models.FoodItem", b =>
                {
                    b.Navigation("MealFoodItems");
                });

            modelBuilder.Entity("Flush_API.Models.Meal", b =>
                {
                    b.Navigation("MealFoodItems");
                });
#pragma warning restore 612, 618
        }
    }
}
